/* tslint:disable */
/* eslint-disable */
/**
 * Splat3Api
 * このAPIは、Splatoon3の関連データを取得するための非公式APIです。  ## Rate Limit  このAPIには、1分あたり100回のレート制限があります。どのエンドポイントにおいても、以下のようなレスポンスヘッダーが含まれています。  ``` RateLimit-Limit: 100 RateLimit-Remaining: 99 RateLimit-Reset: 589 ```  - `RateLimit-Limit`はレート制限の基準数です。この値を超えると、再度リクエストを送信できるようになるまでブロックされます。 - `RateLimit-Remaining`は残りのリクエスト回数です。 - `RateLimit-Reset`は`RateLimit-Remaining`がリセットされるまでの秒数です。  レート制限はIPごとに行われます。また、すべてのリクエストがカウントの対象であり、どのレスポンスであっても1リクエストとしてカウントされます。  - 404 Not Found - 400 Bad Request - 204 No Content - 200 OK
 *
 * The version of the OpenAPI document: 0.0.17-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Schedule } from './Schedule';
import {
    ScheduleFromJSON,
    ScheduleFromJSONTyped,
    ScheduleToJSON,
} from './Schedule';

/**
 * `regular match`, `bankaraMatch Open`, `bankaraMatch Challenge`, `Salmon Run`, `X Battle`のスケジュール。
 * @export
 * @interface AllSchedule
 */
export interface AllSchedule {
    /**
     * 
     * @type {Array<Schedule>}
     * @memberof AllSchedule
     */
    bankaraOpenSchedules?: Array<Schedule>;
    /**
     * 
     * @type {Array<Schedule>}
     * @memberof AllSchedule
     */
    bankaraChallengeSchedules?: Array<Schedule>;
    /**
     * 
     * @type {Array<Schedule>}
     * @memberof AllSchedule
     */
    regularSchedules?: Array<Schedule>;
    /**
     * 
     * @type {Array<Schedule>}
     * @memberof AllSchedule
     */
    salmonRunSchedules?: Array<Schedule>;
    /**
     * 
     * @type {Array<Schedule>}
     * @memberof AllSchedule
     */
    xSchedules?: Array<Schedule>;
}

/**
 * Check if a given object implements the AllSchedule interface.
 */
export function instanceOfAllSchedule(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AllScheduleFromJSON(json: any): AllSchedule {
    return AllScheduleFromJSONTyped(json, false);
}

export function AllScheduleFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllSchedule {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bankaraOpenSchedules': !exists(json, 'bankaraOpenSchedules') ? undefined : ((json['bankaraOpenSchedules'] as Array<any>).map(ScheduleFromJSON)),
        'bankaraChallengeSchedules': !exists(json, 'bankaraChallengeSchedules') ? undefined : ((json['bankaraChallengeSchedules'] as Array<any>).map(ScheduleFromJSON)),
        'regularSchedules': !exists(json, 'regularSchedules') ? undefined : ((json['regularSchedules'] as Array<any>).map(ScheduleFromJSON)),
        'salmonRunSchedules': !exists(json, 'salmonRunSchedules') ? undefined : ((json['salmonRunSchedules'] as Array<any>).map(ScheduleFromJSON)),
        'xSchedules': !exists(json, 'xSchedules') ? undefined : ((json['xSchedules'] as Array<any>).map(ScheduleFromJSON)),
    };
}

export function AllScheduleToJSON(value?: AllSchedule | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bankaraOpenSchedules': value.bankaraOpenSchedules === undefined ? undefined : ((value.bankaraOpenSchedules as Array<any>).map(ScheduleToJSON)),
        'bankaraChallengeSchedules': value.bankaraChallengeSchedules === undefined ? undefined : ((value.bankaraChallengeSchedules as Array<any>).map(ScheduleToJSON)),
        'regularSchedules': value.regularSchedules === undefined ? undefined : ((value.regularSchedules as Array<any>).map(ScheduleToJSON)),
        'salmonRunSchedules': value.salmonRunSchedules === undefined ? undefined : ((value.salmonRunSchedules as Array<any>).map(ScheduleToJSON)),
        'xSchedules': value.xSchedules === undefined ? undefined : ((value.xSchedules as Array<any>).map(ScheduleToJSON)),
    };
}

