/* tslint:disable */
/* eslint-disable */
/**
 * Splat3Api
 * このAPIは、Splatoon3の関連データを取得するための非公式APIです。  ## Rate Limit  このAPIには、1分あたり100回のレート制限があります。どのエンドポイントにおいても、以下のようなレスポンスヘッダーが含まれています。  ``` RateLimit-Limit: 100 RateLimit-Remaining: 99 RateLimit-Reset: 589 ```  - `RateLimit-Limit`はレート制限の基準数です。この値を超えると、再度リクエストを送信できるようになるまでブロックされます。 - `RateLimit-Remaining`は残りのリクエスト回数です。 - `RateLimit-Reset`は`RateLimit-Remaining`がリセットされるまでの秒数です。  レート制限はIPごとに行われます。また、すべてのリクエストがカウントの対象であり、どのレスポンスであっても1リクエストとしてカウントされます。  - 404 Not Found - 400 Bad Request - 204 No Content - 200 OK
 *
 * The version of the OpenAPI document: 0.0.21-alpha
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Area, Tower, Clam, Rainmaker
 * @export
 */
export const GameMode = {
    Area: 'Area',
    Clam: 'Clam',
    Tower: 'Tower',
    Rainmaker: 'Rainmaker'
} as const;
export type GameMode = typeof GameMode[keyof typeof GameMode];


export function GameModeFromJSON(json: any): GameMode {
    return GameModeFromJSONTyped(json, false);
}

export function GameModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameMode {
    return json as GameMode;
}

export function GameModeToJSON(value?: GameMode | null): any {
    return value as any;
}

